### ISSUE TITLE
Use AsFd/AsHandle once that lands in rust stable

### ISSUE THREAD

**Issue by passcod** [watchexec/command-group#1]
Tokio support will need a PR to convert, which will depend on Tokio's MSRV

**Comment by mjpieters** [comment]
What is the intention here, to give access to the handles for the process streams, or is the windows job object handle in scope here too?

**Comment by passcod** [comment]
No, this is an internal change, to change to the safer BorrowedFd instead of RawFd if possible.

**Comment by passcod** [comment]
Upon examination, this doesn't make sense anymore.
