### ISSUE TITLE
v2.1.1 breaks watchexec

### ISSUE THREAD

**Issue by aobatact** [watchexec/command-group#24]
v2.1.1 bumps up the dependencies of nix to `0.26.1` to `0.27.1` (https://github.com/watchexec/command-group/commit/27ea553905734dc3dc267cb6bbc99b60b5f10ca1) , but this breaks `watchexec` crate. (https://github.com/watchexec/watchexec/issues/669)

**Comment by passcod** [comment]
Oh, ugh, I'd hoped this wouldn't happen.

**Comment by passcod** [comment]
Yanked 2.1.1 and published 3.0.0.
