### ISSUE TITLE
`kill_on_drop` is used only on windows

### ISSUE THREAD

**Issue by meskill** [watchexec/command-group#29]
[`kill_on_drop`](https://docs.rs/command-group/5.0.1/command_group/builder/struct.CommandGroupBuilder.html#method.kill_on_drop) according to the source code affecting only windows implementation whilst for unix it does nothing. 

It's quite confusing and unexpected. 

Suggestion: add `kill_on_drop` support for unix implementation also.

**Comment by passcod** [comment]
this library has been superheded by process-wrap
